name: Build PDFs

on:
  push:
    paths:
      - '2019 submission/xsede.tex'
      - '2019 submission/performance.tex'
      - '.github/workflows/build-pdfs.yml'
  pull_request:
    paths:
      - '2019 submission/xsede.tex'
      - '2019 submission/performance.tex'
      - '.github/workflows/build-pdfs.yml'
  workflow_dispatch:

jobs:
  build-pdfs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install TeX Live (pdflatex)
        run: sudo apt-get update && sudo apt-get install -y texlive-latex-base

      - name: Build xsede.pdf
        run: pdflatex xsede.tex
        working-directory: 2019 submission

      - name: Build performance.pdf
        run: pdflatex performance.tex
        working-directory: 2019 submission
