name: Build PDFs

on:
  push:
    paths:
      - '2019 submission/xsede.tex'
      - '2019 submission/performance.tex'
      - '.github/workflows/build-pdfs.yml'
  pull_request:
    paths:
      - '2019 submission/xsede.tex'
      - '2019 submission/performance.tex'
      - '.github/workflows/build-pdfs.yml'
  workflow_dispatch:

jobs:
  build-pdfs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install TeX Live (pdflatex and extras)
        run: sudo apt-get update && sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-science texlive-pictures

      - name: Build xsede.pdf in parent directory
        run: pdflatex xsede.tex
        working-directory: 2019 submission

      - name: Build performance.pdf in parent directory
        run: pdflatex performance.tex
        working-directory: 2019 submission

      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdfs
          path: |
            2019 submission/xsede.pdf
            2019 submission/performance.pdf
